python main.py \
        --device cuda \
        --batch_size 60  \
        --n_head 12 \
        --n_layer 12 \
        --n_embd 768 \
        --d_dropout 0.0 \
        --dropout 0.0 \
        --lr_start 1e-5 \
        --num_workers 20\
        --max_epochs 1000 \
        --num_feats 32 \
        --checkpoint_every 10 \
        --seed_path './Pretrained MoLFormer/checkpoints/N-Step-Checkpoint_3_30000.ckpt' \
        --dataset_name FD_A0 \
        --data_root ./data/FD_A0 \
        --measure_name CCS \
        --checkpoints_folder './Linear_Full_A0'\
        --project_name 'Linear_Full_A0' \
        --type 'early' \
        --adduct_num 10 \
        --ecfp_num 1024 \